Repository kyma-incubator/varkes, pull requests merged in 2021-11, with the labels that each got.

#295 Extend Varkes to Support Cloud Events
  examples/kyma-mock/apis/connector.yaml
  examples/kyma-mock/apis/events.yaml
  examples/kyma-mock/app.js
  examples/kyma-mock/package-lock.json
  examples/openapi-mock/package-lock.json
  modules/api-server/src/server/app.ts
  modules/api-server/src/server/routes/events.ts
  modules/api-server/src/test/test.ts
  modules/app-connector/src/server/connection.ts
  modules/app-connector/src/server/event.ts
  modules/app-connector/src/server/kyma/connector.ts
  modules/app-connector/src/server/kyma/event.ts
  modules/app-connector/src/test/expect/cloudevent.json
  modules/app-connector/src/test/expect/cloudeventbinary.json
  modules/app-connector/src/test/expect/event.json
  modules/app-connector/src/test/test.ts
  modules/cockpit/package-lock.json
  modules/cockpit/package.json
  modules/cockpit/src/app/sendEventView/app.send.eventview.html
  modules/cockpit/src/app/sendEventView/send.eventview.ts
  modules/configuration/package-lock.json
  modules/openapi-mock/src/server/app.ts
Labels: lgtm, size/XXL

#300 bumb version to 0.13.0
  examples/combined-odata-mock/package-lock.json
  examples/combined-odata-mock/package.json
  examples/combined-openapi-mock/package-lock.json
  examples/combined-openapi-mock/package.json
  examples/kyma-mock/package-lock.json
  examples/kyma-mock/package.json
  examples/odata-mock/package-lock.json
  examples/odata-mock/package.json
  examples/openapi-mock/package-lock.json
  examples/openapi-mock/package.json
  lerna.json
  modules/api-server/package-lock.json
  modules/api-server/package.json
  modules/app-connector/package-lock.json
  modules/app-connector/package.json
  modules/cockpit/package-lock.json
  modules/cockpit/package.json
  modules/configuration/package-lock.json
  modules/configuration/package.json
  modules/odata-mock/package-lock.json
  modules/odata-mock/package.json
  modules/openapi-mock/package-lock.json
  modules/openapi-mock/package.json
Labels: size/M

#301 Fix varkes release
  Makefile
Labels: size/XS, lgtm
